### ISSUE TITLE
Gem contentful-exporter is not available

### ISSUE THREAD

**Issue by ivarprudnikov** [Instrument/contentful-exporter.rb#2]
$: gem -v
    2.4.8

    $: gem search contentful

    *** REMOTE GEMS ***

    contentful (0.5.0)
    contentful-importer (0.2.1)
    contentful-management (0.7.1)
    contentful_middleman (1.1.1)
    contentful_model (0.1.7.1)
    contentful_rails (0.2.2.2)
    storageroom-to-contentful (0.0.5)

    $: gem install contentful-exporter
    ERROR:  Could not find a valid gem 'contentful-exporter' (>= 0) in any repository
    ERROR:  Possible alternatives: contentful-importer, context_exposer, contentful_model, content_server, cal_exporter

**Comment by Varun-Krishna-P** [comment]
@ivarprudnikov 
There is one workaround for this. 
1. git clone https://github.com/Instrument/contentful-exporter.rb.git
2. Build Gem:
    cd <% cloned directory%> && gem build contentful_exporter.gemspec
3. gem install contentful-exporter-0.1.gem
more information at http://stackoverflow.com/questions/16365146/install-ruby-gem-globally-from-github-repository

**Comment by nijotz** [comment]
I didn't want to publish a gem because I feel this should be Contentful's project.  I needed this for a project at work and decided to share in case others need something similar.

**Comment by nijotz** [comment]
Thanks @Varun-Krishna-P for providing instructions

**Comment by ivarprudnikov** [comment]
Thanks @Varun-Krishna-P for instructions and thanks @nijotz for code. I haven't done Ruby before, so it wasn't clear that I needed to build gem.
Hopefully this issue will be helpful to someone else.
